server:
  port: 7979
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    status-page-url: http://${spring.cloud.client.ipAddress}:${server.port}/swagger-ui.html
spring:
  application:
    name: discovery-service