spring:
  rabbitmq:
    host: 52.74.213.195
    port: 5672
    username: root
    password: admin
server:
  port: 2010
env: dev
management:
  endpoints:
    web:
      exposure:
        include: routes

