spring:
  rabbitmq:
    host: 52.74.213.195
    port: 5672
    username: guest
    password: guest
  zipkin:
    base-url: http://52.74.213.195:9411/
  sleuth:
    sampler:
      probability: 1
server:
  port: 2011
env: dev
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 15000
        readTimeout: 15000
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream, info, health
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 15000
