spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: admin
server:
  port: 2011
env: dev
feign:
  hystrix:
    enabled: true
feign:
  client:
    config:
      default:
        connectTimeout: 15000
        readTimeout: 15000
        loggerLevel: basic