spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: admin
server:
  port: 2011
env: dev
feign:
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream, info, health
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 15000